{% set name = "gssapi" %}
{% set version = "1.11.1" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2049ee4b1d0c363163a1344b7282a363f9f4094e51d2c36de0cf01d4735e0ae2
  patches:
    - 0001-fix-setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]
  script_env:
    - GSSAPI_SUPPORT_DETECT=false  # [build_platform != target_platform]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.3,<4.0.0a0                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=3.0.3,<4.0.0a0
    - krb5
    - pip
    - setuptools >=40.6.0
  run:
    - python
    - decorator

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  doc_url: https://pythongssapi.github.io/python-gssapi/stable/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
