{% set name = "gssapi" %}
{% set version = "1.6.14" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bb0a41c9985ad78b973aa3c9f1fa200b543013e3a1b2a24463c2e5d8d1afaf1
  patches:
    - 0001-fix-setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - krb5
    - pip
  run:
    - python
    - decorator

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  doc_url: https://pythongssapi.github.io/python-gssapi/stable/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
